version: 2
updates:
  # Maintain dependencies for Node.js (React Frontend)
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
      
  # Maintain dependencies for Python (FastAPI Backend)
  - package-ecosystem: "pip"
    directory: "/backend"
    schedule:
      interval: "weekly"
