import pandas as pd

class FeatureEngineeringService:
    @staticmethod
    def engineer_features(df: pd.DataFrame) -> pd.DataFrame:
        """
        Dynamically engineer features based on what columns are present in the dataset.
        In a real scenario, this applies complex transformations.
        """
        engineered_df = df.copy()
        
        # Example 1: Average Internal Marks
        internal_cols = [col for col in df.columns if 'CAE' in col or 'Quiz' in col or 'Assignment' in col]
        if internal_cols:
            engineered_df['Average_Internal'] = engineered_df[internal_cols].mean(axis=1)
            
        # Example 2: Trend Calculation (CAE2 - CAE1)
        if 'CAE1' in df.columns and 'CAE2' in df.columns:
            engineered_df['Performance_Trend'] = engineered_df['CAE2'] - engineered_df['CAE1']
            
        # Example 3: Academic Consistency (Standard Deviation of internals)
        if len(internal_cols) > 1:
            engineered_df['Assessment_Consistency'] = engineered_df[internal_cols].std(axis=1)
            
        # Fill any NaNs generated by engineering
        engineered_df.fillna(0, inplace=True)
        
        return engineered_df
