"""Add Phase 6 ML Models

Revision ID: 56ddee71368f
Revises: d5303b8133d4
Create Date: 2026-07-22 23:49:08.563197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56ddee71368f'
down_revision: Union[str, Sequence[str], None] = 'd5303b8133d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ml_datasets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version_name', sa.String(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('record_count', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('features_list', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['uploaded_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ml_datasets_id'), 'ml_datasets', ['id'], unique=False)
    op.create_index(op.f('ix_ml_datasets_version_name'), 'ml_datasets', ['version_name'], unique=True)
    op.create_table('ml_trained_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(), nullable=True),
    sa.Column('algorithm', sa.String(), nullable=True),
    sa.Column('target_type', sa.String(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('rmse', sa.Float(), nullable=True),
    sa.Column('r2_score', sa.Float(), nullable=True),
    sa.Column('dataset_id', sa.Integer(), nullable=True),
    sa.Column('trained_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['ml_datasets.id'], ),
    sa.ForeignKeyConstraint(['trained_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ml_trained_models_id'), 'ml_trained_models', ['id'], unique=False)
    op.create_index(op.f('ix_ml_trained_models_model_name'), 'ml_trained_models', ['model_name'], unique=False)
    op.create_table('ml_feature_importance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=True),
    sa.Column('feature_name', sa.String(), nullable=True),
    sa.Column('importance_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['ml_trained_models.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ml_feature_importance_id'), 'ml_feature_importance', ['id'], unique=False)
    op.create_table('ml_prediction_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('model_id', sa.Integer(), nullable=True),
    sa.Column('target_type', sa.String(), nullable=True),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('predicted_value', sa.Float(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('risk_level', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['ml_trained_models.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ml_prediction_history_id'), 'ml_prediction_history', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ml_prediction_history_id'), table_name='ml_prediction_history')
    op.drop_table('ml_prediction_history')
    op.drop_index(op.f('ix_ml_feature_importance_id'), table_name='ml_feature_importance')
    op.drop_table('ml_feature_importance')
    op.drop_index(op.f('ix_ml_trained_models_model_name'), table_name='ml_trained_models')
    op.drop_index(op.f('ix_ml_trained_models_id'), table_name='ml_trained_models')
    op.drop_table('ml_trained_models')
    op.drop_index(op.f('ix_ml_datasets_version_name'), table_name='ml_datasets')
    op.drop_index(op.f('ix_ml_datasets_id'), table_name='ml_datasets')
    op.drop_table('ml_datasets')
    # ### end Alembic commands ###
