"""Add Phase 3 Assessment Modules

Revision ID: 788a29373276
Revises: 9990ddd615a0
Create Date: 2026-07-19 17:35:08.607239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '788a29373276'
down_revision: Union[str, Sequence[str], None] = '9990ddd615a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessment_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessment_type_id'), 'assessment_type', ['id'], unique=False)
    op.create_index(op.f('ix_assessment_type_name'), 'assessment_type', ['name'], unique=True)
    op.create_table('assessment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assessment_name', sa.String(), nullable=True),
    sa.Column('assessment_type_id', sa.Integer(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('semester_id', sa.Integer(), nullable=True),
    sa.Column('academic_year_id', sa.Integer(), nullable=True),
    sa.Column('faculty_id', sa.Integer(), nullable=True),
    sa.Column('maximum_marks', sa.Float(), nullable=True),
    sa.Column('passing_marks', sa.Float(), nullable=True),
    sa.Column('weightage', sa.Float(), nullable=True),
    sa.Column('schedule_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_year.id'], ),
    sa.ForeignKeyConstraint(['assessment_type_id'], ['assessment_type.id'], ),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['faculty_id'], ['faculty.id'], ),
    sa.ForeignKeyConstraint(['semester_id'], ['semester.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessment_assessment_name'), 'assessment', ['assessment_name'], unique=False)
    op.create_index(op.f('ix_assessment_id'), 'assessment', ['id'], unique=False)
    op.create_table('course_outcome',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('co_number', sa.String(), nullable=True),
    sa.Column('co_title', sa.String(), nullable=True),
    sa.Column('co_description', sa.String(), nullable=True),
    sa.Column('target_percentage', sa.Float(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_course_outcome_co_number'), 'course_outcome', ['co_number'], unique=False)
    op.create_index(op.f('ix_course_outcome_id'), 'course_outcome', ['id'], unique=False)
    op.create_table('question_bank',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('unit', sa.Integer(), nullable=True),
    sa.Column('question_number', sa.String(), nullable=True),
    sa.Column('question_text', sa.String(), nullable=True),
    sa.Column('maximum_marks', sa.Float(), nullable=True),
    sa.Column('question_type', sa.String(), nullable=True),
    sa.Column('difficulty_level', sa.String(), nullable=True),
    sa.Column('bloom_level', sa.String(), nullable=True),
    sa.Column('co_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['co_id'], ['course_outcome.id'], ),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_bank_id'), 'question_bank', ['id'], unique=False)
    op.create_table('student_mark',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('assessment_id', sa.Integer(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('marks_obtained', sa.Float(), nullable=True),
    sa.Column('remarks', sa.String(), nullable=True),
    sa.Column('attendance_status', sa.String(), nullable=True),
    sa.Column('is_final_submission', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessment.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['question_bank.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_mark_id'), 'student_mark', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_mark_id'), table_name='student_mark')
    op.drop_table('student_mark')
    op.drop_index(op.f('ix_question_bank_id'), table_name='question_bank')
    op.drop_table('question_bank')
    op.drop_index(op.f('ix_course_outcome_id'), table_name='course_outcome')
    op.drop_index(op.f('ix_course_outcome_co_number'), table_name='course_outcome')
    op.drop_table('course_outcome')
    op.drop_index(op.f('ix_assessment_id'), table_name='assessment')
    op.drop_index(op.f('ix_assessment_assessment_name'), table_name='assessment')
    op.drop_table('assessment')
    op.drop_index(op.f('ix_assessment_type_name'), table_name='assessment_type')
    op.drop_index(op.f('ix_assessment_type_id'), table_name='assessment_type')
    op.drop_table('assessment_type')
    # ### end Alembic commands ###
