"""Add missing fields for Phase 1

Revision ID: 83a5d32be283
Revises: 8a5803302280
Create Date: 2026-07-19 16:50:34.435758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '83a5d32be283'
down_revision: Union[str, Sequence[str], None] = '8a5803302280'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('academic_year', sa.Column('status', sa.Boolean(), nullable=True))
    op.alter_column('academic_year', 'academic_year',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('academic_year', 'start_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('academic_year', 'end_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.drop_index(op.f('ix_academic_year_academic_year'), table_name='academic_year')
    op.create_index(op.f('ix_academic_year_academic_year'), 'academic_year', ['academic_year'], unique=False)
    op.add_column('course', sa.Column('duration', sa.Integer(), nullable=True))
    op.add_column('course', sa.Column('status', sa.Boolean(), nullable=True))
    op.add_column('course', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('course', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('course', 'course_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('course', 'course_code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('course', 'department_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('course', 'semester')
    op.add_column('department', sa.Column('hod_name', sa.String(), nullable=True))
    op.add_column('department', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('department', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('department', 'department_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('department', 'department_code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(op.f('department_hod_id_fkey'), 'department', type_='foreignkey')
    op.drop_column('department', 'hod_id')
    op.add_column('faculty', sa.Column('status', sa.Boolean(), nullable=True))
    op.alter_column('faculty', 'faculty_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('faculty', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('faculty', 'department_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('faculty_user_id_fkey'), 'faculty', type_='foreignkey')
    op.drop_column('faculty', 'user_id')
    op.alter_column('semester', 'semester_number',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('semester', 'academic_year_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('student', 'student_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('student', 'roll_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('student', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('student', 'department_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('student', 'course_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('student', 'semester_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('student_user_id_fkey'), 'student', type_='foreignkey')
    op.drop_column('student', 'user_id')
    op.add_column('subject', sa.Column('credits', sa.Integer(), nullable=True))
    op.add_column('subject', sa.Column('status', sa.Boolean(), nullable=True))
    op.alter_column('subject', 'subject_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('subject', 'subject_code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('subject', 'semester',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('subject', 'course_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user', 'role',
               existing_type=postgresql.ENUM('ADMIN', 'HOD', 'FACULTY', 'STUDENT', name='userrole'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'role',
               existing_type=postgresql.ENUM('ADMIN', 'HOD', 'FACULTY', 'STUDENT', name='userrole'),
               nullable=False)
    op.alter_column('subject', 'course_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('subject', 'semester',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('subject', 'subject_code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('subject', 'subject_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('subject', 'status')
    op.drop_column('subject', 'credits')
    op.add_column('student', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('student_user_id_fkey'), 'student', 'user', ['user_id'], ['id'])
    op.alter_column('student', 'semester_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('student', 'course_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('student', 'department_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('student', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('student', 'roll_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('student', 'student_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('semester', 'academic_year_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('semester', 'semester_number',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('faculty', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('faculty_user_id_fkey'), 'faculty', 'user', ['user_id'], ['id'])
    op.alter_column('faculty', 'department_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('faculty', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('faculty', 'faculty_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('faculty', 'status')
    op.add_column('department', sa.Column('hod_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('department_hod_id_fkey'), 'department', 'user', ['hod_id'], ['id'])
    op.alter_column('department', 'department_code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('department', 'department_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('department', 'updated_at')
    op.drop_column('department', 'created_at')
    op.drop_column('department', 'hod_name')
    op.add_column('course', sa.Column('semester', sa.INTEGER(), autoincrement=False, nullable=False))
    op.alter_column('course', 'department_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('course', 'course_code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('course', 'course_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('course', 'updated_at')
    op.drop_column('course', 'created_at')
    op.drop_column('course', 'status')
    op.drop_column('course', 'duration')
    op.drop_index(op.f('ix_academic_year_academic_year'), table_name='academic_year')
    op.create_index(op.f('ix_academic_year_academic_year'), 'academic_year', ['academic_year'], unique=True)
    op.alter_column('academic_year', 'end_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('academic_year', 'start_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('academic_year', 'academic_year',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('academic_year', 'status')
    # ### end Alembic commands ###
