"""Add Phase 2 Academic Modules

Revision ID: 9990ddd615a0
Revises: 83a5d32be283
Create Date: 2026-07-19 17:13:43.307766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9990ddd615a0'
down_revision: Union[str, Sequence[str], None] = '83a5d32be283'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('entity_type', sa.String(), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_action'), 'audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_audit_log_id'), 'audit_log', ['id'], unique=False)
    op.create_index(op.f('ix_audit_log_timestamp'), 'audit_log', ['timestamp'], unique=False)
    op.create_index(op.f('ix_audit_log_user_id'), 'audit_log', ['user_id'], unique=False)
    op.create_table('program',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program_name', sa.String(), nullable=True),
    sa.Column('program_code', sa.String(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('degree_type', sa.String(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_program_id'), 'program', ['id'], unique=False)
    op.create_index(op.f('ix_program_program_code'), 'program', ['program_code'], unique=True)
    op.create_index(op.f('ix_program_program_name'), 'program', ['program_name'], unique=False)
    op.create_table('academic_calendar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('academic_year_id', sa.Integer(), nullable=True),
    sa.Column('semester_id', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('internal_exam_dates', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('practical_dates', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('assignment_deadlines', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('holiday_list', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_year.id'], ),
    sa.ForeignKeyConstraint(['semester_id'], ['semester.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_academic_calendar_id'), 'academic_calendar', ['id'], unique=False)
    op.create_table('batch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_name', sa.String(), nullable=True),
    sa.Column('batch_year', sa.Integer(), nullable=True),
    sa.Column('program_id', sa.Integer(), nullable=True),
    sa.Column('academic_year_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_year.id'], ),
    sa.ForeignKeyConstraint(['program_id'], ['program.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_batch_batch_name'), 'batch', ['batch_name'], unique=False)
    op.create_index(op.f('ix_batch_id'), 'batch', ['id'], unique=False)
    op.create_table('curriculum',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('curriculum_name', sa.String(), nullable=True),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('program_id', sa.Integer(), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('courses_included', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], ),
    sa.ForeignKeyConstraint(['program_id'], ['program.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_curriculum_curriculum_name'), 'curriculum', ['curriculum_name'], unique=False)
    op.create_index(op.f('ix_curriculum_id'), 'curriculum', ['id'], unique=False)
    op.create_table('section',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('section_name', sa.String(), nullable=True),
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.Column('semester_id', sa.Integer(), nullable=True),
    sa.Column('mentor_faculty_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['batch.id'], ),
    sa.ForeignKeyConstraint(['mentor_faculty_id'], ['faculty.id'], ),
    sa.ForeignKeyConstraint(['semester_id'], ['semester.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_section_id'), 'section', ['id'], unique=False)
    op.create_index(op.f('ix_section_section_name'), 'section', ['section_name'], unique=False)
    op.create_table('course_offering',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('faculty_id', sa.Integer(), nullable=True),
    sa.Column('semester_id', sa.Integer(), nullable=True),
    sa.Column('section_id', sa.Integer(), nullable=True),
    sa.Column('academic_year_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_year.id'], ),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['faculty_id'], ['faculty.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['section.id'], ),
    sa.ForeignKeyConstraint(['semester_id'], ['semester.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_course_offering_id'), 'course_offering', ['id'], unique=False)
    op.add_column('student', sa.Column('program_id', sa.Integer(), nullable=True))
    op.add_column('student', sa.Column('batch_id', sa.Integer(), nullable=True))
    op.add_column('student', sa.Column('section_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'student', 'batch', ['batch_id'], ['id'])
    op.create_foreign_key(None, 'student', 'program', ['program_id'], ['id'])
    op.create_foreign_key(None, 'student', 'section', ['section_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'student', type_='foreignkey')
    op.drop_constraint(None, 'student', type_='foreignkey')
    op.drop_constraint(None, 'student', type_='foreignkey')
    op.drop_column('student', 'section_id')
    op.drop_column('student', 'batch_id')
    op.drop_column('student', 'program_id')
    op.drop_index(op.f('ix_course_offering_id'), table_name='course_offering')
    op.drop_table('course_offering')
    op.drop_index(op.f('ix_section_section_name'), table_name='section')
    op.drop_index(op.f('ix_section_id'), table_name='section')
    op.drop_table('section')
    op.drop_index(op.f('ix_curriculum_id'), table_name='curriculum')
    op.drop_index(op.f('ix_curriculum_curriculum_name'), table_name='curriculum')
    op.drop_table('curriculum')
    op.drop_index(op.f('ix_batch_id'), table_name='batch')
    op.drop_index(op.f('ix_batch_batch_name'), table_name='batch')
    op.drop_table('batch')
    op.drop_index(op.f('ix_academic_calendar_id'), table_name='academic_calendar')
    op.drop_table('academic_calendar')
    op.drop_index(op.f('ix_program_program_name'), table_name='program')
    op.drop_index(op.f('ix_program_program_code'), table_name='program')
    op.drop_index(op.f('ix_program_id'), table_name='program')
    op.drop_table('program')
    op.drop_index(op.f('ix_audit_log_user_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_timestamp'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_action'), table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
