"""Add Phase 4 CO Configuration Modules

Revision ID: bdbe2fc5e19e
Revises: 788a29373276
Create Date: 2026-07-20 10:18:41.353322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdbe2fc5e19e'
down_revision: Union[str, Sequence[str], None] = '788a29373276'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attainment_rule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('level_name', sa.String(), nullable=True),
    sa.Column('min_percentage', sa.Float(), nullable=True),
    sa.Column('max_percentage', sa.Float(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attainment_rule_id'), 'attainment_rule', ['id'], unique=False)
    op.create_index(op.f('ix_attainment_rule_level_name'), 'attainment_rule', ['level_name'], unique=True)
    op.create_table('co_configuration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_percentage', sa.Float(), nullable=True),
    sa.Column('calculation_method', sa.String(), nullable=True),
    sa.Column('round_off_rules', sa.String(), nullable=True),
    sa.Column('minimum_student_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_co_configuration_id'), 'co_configuration', ['id'], unique=False)
    op.create_table('assessment_weightage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assessment_type_id', sa.Integer(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('weightage_percentage', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['assessment_type_id'], ['assessment_type.id'], ),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessment_weightage_id'), 'assessment_weightage', ['id'], unique=False)
    op.create_table('co_attainment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('co_id', sa.Integer(), nullable=True),
    sa.Column('assessment_id', sa.Integer(), nullable=True),
    sa.Column('attainment_percentage', sa.Float(), nullable=True),
    sa.Column('attainment_level', sa.String(), nullable=True),
    sa.Column('calculated_on', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('academic_year', sa.String(), nullable=True),
    sa.Column('semester', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessment.id'], ),
    sa.ForeignKeyConstraint(['co_id'], ['course_outcome.id'], ),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_co_attainment_id'), 'co_attainment', ['id'], unique=False)
    op.create_table('co_attainment_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('co_attainment_id', sa.Integer(), nullable=True),
    sa.Column('previous_percentage', sa.Float(), nullable=True),
    sa.Column('new_percentage', sa.Float(), nullable=True),
    sa.Column('calculated_on', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('calculated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['calculated_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['co_attainment_id'], ['co_attainment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_co_attainment_history_id'), 'co_attainment_history', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_co_attainment_history_id'), table_name='co_attainment_history')
    op.drop_table('co_attainment_history')
    op.drop_index(op.f('ix_co_attainment_id'), table_name='co_attainment')
    op.drop_table('co_attainment')
    op.drop_index(op.f('ix_assessment_weightage_id'), table_name='assessment_weightage')
    op.drop_table('assessment_weightage')
    op.drop_index(op.f('ix_co_configuration_id'), table_name='co_configuration')
    op.drop_table('co_configuration')
    op.drop_index(op.f('ix_attainment_rule_level_name'), table_name='attainment_rule')
    op.drop_index(op.f('ix_attainment_rule_id'), table_name='attainment_rule')
    op.drop_table('attainment_rule')
    # ### end Alembic commands ###
