"""Add Phase 5 PO Engine Modules

Revision ID: d5303b8133d4
Revises: bdbe2fc5e19e
Create Date: 2026-07-20 15:08:15.817162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5303b8133d4'
down_revision: Union[str, Sequence[str], None] = 'bdbe2fc5e19e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('po_configuration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_percentage', sa.Float(), nullable=True),
    sa.Column('correlation_scale', sa.Integer(), nullable=True),
    sa.Column('calculation_method', sa.String(), nullable=True),
    sa.Column('attainment_levels', sa.String(), nullable=True),
    sa.Column('passing_rules', sa.String(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_po_configuration_id'), 'po_configuration', ['id'], unique=False)
    op.create_table('program_outcomes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('po_number', sa.String(), nullable=True),
    sa.Column('po_title', sa.String(), nullable=True),
    sa.Column('po_description', sa.Text(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_program_outcomes_id'), 'program_outcomes', ['id'], unique=False)
    op.create_index(op.f('ix_program_outcomes_po_number'), 'program_outcomes', ['po_number'], unique=False)
    op.create_table('program_specific_outcomes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pso_number', sa.String(), nullable=True),
    sa.Column('pso_title', sa.String(), nullable=True),
    sa.Column('pso_description', sa.Text(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_program_specific_outcomes_id'), 'program_specific_outcomes', ['id'], unique=False)
    op.create_index(op.f('ix_program_specific_outcomes_pso_number'), 'program_specific_outcomes', ['pso_number'], unique=False)
    op.create_table('po_attainment_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.String(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('calculated_by', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['calculated_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_po_attainment_history_id'), 'po_attainment_history', ['id'], unique=False)
    op.create_table('co_po_mapping',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('co_id', sa.Integer(), nullable=True),
    sa.Column('po_id', sa.Integer(), nullable=True),
    sa.Column('pso_id', sa.Integer(), nullable=True),
    sa.Column('correlation_level', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['co_id'], ['course_outcome.id'], ),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['po_id'], ['program_outcomes.id'], ),
    sa.ForeignKeyConstraint(['pso_id'], ['program_specific_outcomes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_co_po_mapping_id'), 'co_po_mapping', ['id'], unique=False)
    op.create_table('po_attainment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('po_id', sa.Integer(), nullable=True),
    sa.Column('pso_id', sa.Integer(), nullable=True),
    sa.Column('achieved_percentage', sa.Float(), nullable=True),
    sa.Column('attainment_level', sa.Integer(), nullable=True),
    sa.Column('calculated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['po_id'], ['program_outcomes.id'], ),
    sa.ForeignKeyConstraint(['pso_id'], ['program_specific_outcomes.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_po_attainment_course_id'), 'po_attainment', ['course_id'], unique=False)
    op.create_index(op.f('ix_po_attainment_id'), 'po_attainment', ['id'], unique=False)
    op.create_index(op.f('ix_po_attainment_student_id'), 'po_attainment', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_po_attainment_student_id'), table_name='po_attainment')
    op.drop_index(op.f('ix_po_attainment_id'), table_name='po_attainment')
    op.drop_index(op.f('ix_po_attainment_course_id'), table_name='po_attainment')
    op.drop_table('po_attainment')
    op.drop_index(op.f('ix_co_po_mapping_id'), table_name='co_po_mapping')
    op.drop_table('co_po_mapping')
    op.drop_index(op.f('ix_po_attainment_history_id'), table_name='po_attainment_history')
    op.drop_table('po_attainment_history')
    op.drop_index(op.f('ix_program_specific_outcomes_pso_number'), table_name='program_specific_outcomes')
    op.drop_index(op.f('ix_program_specific_outcomes_id'), table_name='program_specific_outcomes')
    op.drop_table('program_specific_outcomes')
    op.drop_index(op.f('ix_program_outcomes_po_number'), table_name='program_outcomes')
    op.drop_index(op.f('ix_program_outcomes_id'), table_name='program_outcomes')
    op.drop_table('program_outcomes')
    op.drop_index(op.f('ix_po_configuration_id'), table_name='po_configuration')
    op.drop_table('po_configuration')
    # ### end Alembic commands ###
